### ISSUE TITLE
大佬，能否把action的布置再写详细点？0基础看不太懂

### ISSUE THREAD

**Issue by yeli008** [TNanko/Scripts#10]
大佬，能否把action的布置再写详细点？0基础看不太懂

**Comment by TNanko** [comment]
emm ，就是复制 config 文件夹下的 config.yml.example 全部内容，配置相关的信息，创建一个 secrets - CONFIG ，将修改好的配置信息复制进去就可以了。中间可能跳步骤了，建议百度或者 google 。
