### ISSUE TITLE
出现1金币情况该怎么办

### ISSUE THREAD

**Issue by hengwuming** [TNanko/Scripts#11]

**Comment by TNanko** [comment]
你这个就是 body 包的问题，建议重新抓包

**Comment by hengwuming** [comment]
> 你这个就是 body 包的问题，建议重新抓包

可是我是第一天可以获得全额金币，第二天就1金币，重新抓包也是一样的

**Comment by TNanko** [comment]
> > 你这个就是 body 包的问题，建议重新抓包
> 
> 
> 
> 可是我是第一天可以获得全额金币，第二天就1金币，重新抓包也是一样的

你这个问题就是 body 包没抓对，没有第二种情况

**Comment by hengwuming** [comment]
> > > 你这个就是 body 包的问题，建议重新抓包
> > 
> > 
> > 可是我是第一天可以获得全额金币，第二天就1金币，重新抓包也是一样的
> 
> 你这个问题就是 body 包没抓对，没有第二种情况

我是安卓小黄鸟住的包，{"common":{"appid":14xxxx4393,"areaid":5,"qq_ver":"8.5.0.5025","os_ver":"Android 10","mp_ver":"0.38.2","mpos_ver":"1.23.0","brand":"Xiaomi","model":"MI 9","screenWidth":393,"screenHeight":817,"windowWidth":393,"windowHeight":763,"openid":"1014246919","guid":1014246919,"session":"one8azo23aa3xas1y7uba5r266y4tp9e","scene":3003,"source":-1,"hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"bookShelf_myshelf_myBook_C","click2":"push_limitYes_suc_C","route":"pages/book-read/index","refer":"pages/book-shelf/index","options":{"bid":"512557","cid":"1","from":"shelf"},"dis":1609173931010,"ext6":17,"eventID":"bookRead_show_I","type":"shown","ccid":1,"bid":"512557","bookStatus":1,"bookPay":0,"chapterStatus":0,"ext1":{"font":18,"bg":0,"pageMode":1},"from":"bookShelf_myshelf_myBook_C_0_512557"}]}

我看了下，和你给的格式是差不多的

**Comment by hengwuming** [comment]
> > > 你这个就是 body 包的问题，建议重新抓包
> > 
> > 
> > 可是我是第一天可以获得全额金币，第二天就1金币，重新抓包也是一样的
> 
> 你这个问题就是 body 包没抓对，没有第二种情况

我是安卓小黄鸟抓的包，{"common":{"appid":14xxxx4393,"areaid":5,"qq_ver":"8.5.0.5025","os_ver":"Android 10","mp_ver":"0.38.2","mpos_ver":"1.23.0","brand":"Xiaomi","model":"MI 9","screenWidth":393,"screenHeight":817,"windowWidth":393,"windowHeight":763,"openid":"1014246919","guid":1014246919,"session":"one8azo23aa3xas1y7uba5r266y4tp9e","scene":3003,"source":-1,"hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"bookShelf_myshelf_myBook_C","click2":"push_limitYes_suc_C","route":"pages/book-read/index","refer":"pages/book-shelf/index","options":{"bid":"512557","cid":"1","from":"shelf"},"dis":1609173931010,"ext6":17,"eventID":"bookRead_show_I","type":"shown","ccid":1,"bid":"512557","bookStatus":1,"bookPay":0,"chapterStatus":0,"ext1":{"font":18,"bg":0,"pageMode":1},"from":"bookShelf_myshelf_myBook_C_0_512557"}]}

我看了下，和你给的格式是差不多的，除了我看的书是从书架点开的

**Comment by TNanko** [comment]
从书库进去抓

**Comment by hengwuming** [comment]
> 从书库进去抓



> 从书库进去抓

之前我用的都是从书库进去抓的，可是还会出现1金币情况
"common":{"appid":14xxxx4393,"areaid":5,"qq_ver":"8.5.0.5025","os_ver":"Android 10","mp_ver":"0.38.2","mpos_ver":"1.23.0","brand":"Xiaomi","model":"MI 9","screenWidth":393,"screenHeight":817,"windowWidth":393,"windowHeight":763,"openid":"1014246919","guid":1014246919,"session":"5phhq0f3xqk8vej70mdna0sfnrqwzbhl","scene":3001,"source":-1,"hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"bookDetail_bottomBar_read_C","click2":"bookLib_endBook_bookClick_C","route":"pages/book-detail/index","refer":"pages/nav-library/index","options":{"bid":"512557"},"dis":1608973965018,"ext6":77,"eventID":"bookDetail_comment_I","type":"shown","bid":"512557","did":"a000000029L31juVCq000HrN","cl_pos":3,"bookStatus":1,"bookPay":2,"from":"bookLib_endBook_bookClick_C_1_512557"}]

**Comment by TNanko** [comment]
那我也没办法了，如果账号比较少的话，每天点一点吧

**Comment by hengwuming** [comment]
> 那我也没办法了，如果账号比较少的话，每天点一点吧

好，多试试别的方法，解决了我跟你说一下。

**Comment by TNanko** [comment]
> > 那我也没办法了，如果账号比较少的话，每天点一点吧
> 
> 好，多试试别的方法，解决了我跟你说一下。

我有个朋友用的是android，明天我让他在这边回复你一下

**Comment by hengwuming** [comment]
> > > 那我也没办法了，如果账号比较少的话，每天点一点吧
> > 
> > 
> > 好，多试试别的方法，解决了我跟你说一下。
> 
> 我有个朋友用的是android，明天我让他在这边回复你一下

好的，感谢

**Comment by TNanko** [comment]
我问了朋友，好像会抓到几十条，你得慢慢尝试，没得办法。有条件的话还是换个苹果手机吧，苹果薅羊毛比较方便！

**Comment by hengwuming** [comment]
> 我问了朋友，好像会抓到几十条，你得慢慢尝试，没得办法。有条件的话还是换个苹果手机吧，苹果薅羊毛比较方便！

好吧，我多试试
