### ISSUE TITLE
有知道怎么部署群晖的吗

### ISSUE THREAD

**Issue by 345784078** [TNanko/Scripts#12]
群晖只部署过lxk的。直接导入映像就可以了。
这个怎么弄啊。。。

**Comment by TNanko** [comment]
> 群晖只部署过lxk的。直接导入映像就可以了。
> 
> 这个怎么弄啊。。。

emm，如果你能安装 python3 环境，则可以参考 vps 配置的方法或者使用 docker 部署。

**Comment by 345784078** [comment]
不用了 哈 有人弄了映像 直接注册表搜索作者的名字就可以安装容器了

**Comment by TNanko** [comment]
好的
