### ISSUE TITLE
请问headers怎么抓包

### ISSUE THREAD

**Issue by b911ss** [TNanko/Scripts#13]
其他两个都搞定了直接复制就行，就是这个我反复对比示例感觉格式不对呢，麻烦大佬在哪搞出来示例（{"ywsession":"08nexxxxxxxxxx6kn6hx","Cookie":"ywguid=2xxxxxxxx8;ywkey=ywbxxxxxurwjS;platform=ios;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0;platform=ios;openid=B9A021EXXXXXXXXXXX18348A2F779","Connection":"keep-alive","Content-Type":"application/json","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.30.0/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","mpversion":"0.30.0"}
）这种格式
![496%HSG R2TWV`2NV0_7X83](https://user-images.githubusercontent.com/18023172/103212275-52767c80-4945-11eb-9af1-3d2b88e03f02.png)

**Comment by TNanko** [comment]
我是用代理软件修改重写的（这个在教程里面有些），然后进入企鹅读书随便看本书获取 headers 。

**Comment by b911ss** [comment]
> 我是用代理软件修改重写的（这个在教程里面有些），然后进入企鹅读书随便看本书获取标题。

那我在研究一下 谢谢大佬
