### ISSUE TITLE
你们用的什么抓包工具

### ISSUE THREAD

**Issue by xushen1994** [TNanko/Scripts#19]
我用fiddler抓包，qq阅读直接没网，其他app有网，是什么原因呢。

**Comment by TNanko** [comment]
> 我用fiddler抓包，qq阅读直接没网，其他app有网，是什么原因呢。

我是ios，用的surge、quanx，loon

**Comment by moetype** [comment]
> 我用fiddler抓包，qq阅读直接没网，其他app有网，是什么原因呢。

手机有没有导入fiddler的ca证书。

> 我用fiddler抓包，qq阅读直接没网，其他app有网，是什么原因呢。

手机有没有导入fiddler的ca证书。

**Comment by xushen1994** [comment]
解决了，没有认真审题。。我跑去抓下载的QQ阅读软件了。。。

**Comment by xushen1994** [comment]
已解决
