### ISSUE TITLE
各位的群晖能跑了吗 

### ISSUE THREAD

**Issue by 345784078** [TNanko/Scripts#20]
我折腾了两天 都没有跑 
bash 里手动python3 ./scripts/qq_read.py没问题
今天在bash里手动运行了一下crond -f 发现好像可以了。。
是不是作者的启动sh里面 要加一下这个进程呢？我小白啥都不懂

**Comment by TNanko** [comment]
> 我折腾了两天 都没有跑
> bash 里手动python3 ./scripts/qq_read.py没问题
> 今天在bash里手动运行了一下crond -f 发现好像可以了。。
> 是不是作者的启动sh里面 要加一下这个进程呢？我小白啥都不懂

理论上只要机器可以运行python3就可以跑程序，关于不能跑，你检查一下你的定时任务是否设置正确并且正常执行（你可以先把时间间隔设置小一点，定时任务路径最好填绝对路径）。
