### ISSUE TITLE
29号就不能跑任务了，也没LOG生成，重装了几次docker镜像也不行，换COOKIES也不行，作者这是怎么了

### ISSUE THREAD

**Issue by wifisky-feilian** [TNanko/Scripts#21]
29号就不能跑任务了，也没LOG生成，重装了几次docker镜像也不行，换COOKIES也不行，作者这是怎么了

**Comment by hongyunfei** [comment]
更新过后docker定时任务不会启动了，不知道哪里的问题

**Comment by wifisky-feilian** [comment]
刚在github action下测试了三次，可以跑任务，但NAS中的docker下的安装还是不跑任务（29号就不能跑任务了，也没LOG生成，重装了几次docker镜像也不行，换COOKIES也不行）

**Comment by TNanko** [comment]
稍等，我去联系一些 pr docker方案的作者，晚点给你们回复

**Comment by EvineDeng** [comment]
@hongyunfei @wifisky-feilian 没有log，现在在等作者@TNanko 直接在py脚本中加入log模块。

**Comment by EvineDeng** [comment]
现在你们可以直接进入容器中
```
# 进入容器
docker exec -it tnanko_scripts bash

cd /Scripts/scripts && python qq_read.py
```
如果正常就是正常的。

**Comment by wifisky-feilian** [comment]
config.yml参数设置会的也是最新的里面的，29日晚上11点开始不跑任务之前挺稳的。另外建议参考一下lxk0301/jd_scripts这个脚本及其里的docker，自动更新及时稳，跑任务也稳。

**Comment by EvineDeng** [comment]
> config.yml参数设置会的也是最新的里面的，29日晚上11点开始不跑任务之前挺稳的。另外建议参考一下lxk0301/jd_scripts这个脚本及其里的docker，自动更新及时稳，跑任务也稳。

tnanko这个脚本不是不能自动更新，是更新了就跑不了，逻辑不一样。最新的镜像是可以跑了，我不测试好我会放上来，只是目前没有日志，要等作者py脚本中加入日志功能。

**Comment by wifisky-feilian** [comment]
不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了

**Comment by wifisky-feilian** [comment]
> > config.yml参数设置会的也是最新的里面的，29日晚上11点开始不跑任务之前挺稳的。另外建议参考一下lxk0301/jd_scripts这个脚本及其里的docker，自动更新及时稳，跑任务也稳。
> 
> tnanko这个脚本不是不能自动更新，是更新了就跑不了，逻辑不一样。最新的镜像是可以跑的，我不测试好我也不会放上来，只是目前没有日志，要等作者py脚本中加入日志功能。

**Comment by EvineDeng** [comment]
> 不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了

我测试是跑的，你们可以试下最新的镜像。crontab -l 看看，会有以下任务存在：
```
*/10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
```

**Comment by wifisky-feilian** [comment]
> crontab -l
进行容器里运行crontab -l是吧？

**Comment by wifisky-feilian** [comment]
> > 不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了
> 
> 我测试是跑的，你们可以试下最新的镜像。crontab -l 看看，会有以下任务存在：
> 
> ```
> */10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
> 10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
> ```

进容器里运行crontab -l是吧？

**Comment by EvineDeng** [comment]
> > > 不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了
> > 
> > 
> > 我测试是跑的，你们可以试下最新的镜像。crontab -l 看看，会有以下任务存在：
> > ```
> > */10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
> > 10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
> > ```
> 
> 进容器里运行crontab -l是吧？

对

**Comment by wifisky-feilian** [comment]
> > > > 不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了
> > > 
> > > 
> > > 我测试是跑的，你们可以试下最新的镜像。crontab -l 看看，会有以下任务存在：
> > > ```
> > > */10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
> > > 10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
> > > ```
> > 
> > 
> > 进容器里运行crontab -l是吧？
> 
> 对

那我再重新下载镜像试试，你们有QQ号或群么？有问题反馈及时些

**Comment by wifisky-feilian** [comment]
> > > > > 不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了
> > > > 
> > > > 
> > > > 我测试是跑的，你们可以试下最新的镜像。crontab -l 看看，会有以下任务存在：
> > > > ```
> > > > */10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
> > > > 10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
> > > > ```
> > > 
> > > 
> > > 进容器里运行crontab -l是吧？
> > 
> > 
> > 对
> 
> 那我再重新下载镜像试试，你们有QQ号或群么？有问题反馈及时些

配置好config.yml，重新下载镜像只运行正常还是不跑任务，进容器里运行crontab -l有
*/10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
但是还是不跑任务，等了半小时，只好在容器里运行crond，运行后就跑任务了，觉得还是安装脚本哪里在安装时把crond服务关了或者没启动起来的问题造成的，小白不是太懂，只是猜想
