### ISSUE TITLE
再咨询个Actions的问题，QQ阅读，我在actions里只创建了一下运行，为什么过段时间，出现好多运行的“企鹅读书”？

### ISSUE THREAD

**Issue by wifisky-feilian** [TNanko/Scripts#22]
由于最新docker只运行不跑任务，只好用Actions跑任务了。再咨询个Actions的问题，QQ阅读，我在actions里只创建了一下运行，为什么过段时间，出现好多运行的“企鹅读书”？而bilibili 签到却一直是一个正常运行呢？头次用Actions玩，这情况也是第一次见。不知道什么原因？

**Comment by TNanko** [comment]
> 由于最新docker只运行不跑任务，只好用Actions跑任务了。再咨询个Actions的问题，QQ阅读，我在actions里只创建了一下运行，为什么过段时间，出现好多运行的“企鹅读书”？而bilibili 签到却一直是一个正常运行呢？头次用Actions玩，这情况也是第一次见。不知道什么原因？

因为企鹅读书是 10 分钟运行一次，而 b 站签到是一天一次
关于 docker 只运行不跑任务我会进步排查问题

**Comment by TNanko** [comment]
> 由于最新docker只运行不跑任务，只好用Actions跑任务了。再咨询个Actions的问题，QQ阅读，我在actions里只创建了一下运行，为什么过段时间，出现好多运行的“企鹅读书”？而bilibili 签到却一直是一个正常运行呢？头次用Actions玩，这情况也是第一次见。不知道什么原因？

你用 v1.4.0 版本（最新一个版本）的docker试试
