### ISSUE TITLE
> > > > > 不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了

### ISSUE THREAD

**Issue by wifisky-feilian** [TNanko/Scripts#24]
> > > > > 不是有没有日志的问题，是QQ上没金币产生，也叫不跑任务。我用3个NAS得新测试了一下，容器运行是很稳的，就是不跑任务，某群管理说要运行一下crond才行，这个群有几个也用的你们这个脚本的docker镜像，我问了一下也是这几天都不跑任务了
> > > > 
> > > > 
> > > > 我测试是跑的，你们可以试下最新的镜像。crontab -l 看看，会有以下任务存在：
> > > > ```
> > > > */10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
> > > > 10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
> > > > ```
> > > 
> > > 
> > > 进容器里运行crontab -l是吧？
> > 
> > 
> > 对
> 
> 那我再重新下载镜像试试，你们有QQ号或群么？有问题反馈及时些

配置好config.yml，重新下载镜像只运行正常还是不跑任务，进容器里运行crontab -l有
*/10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts
10 1 * * * python3 /Scripts/scripts/bilibili.py # TNanko Scripts
但是还是不跑任务，等了半小时，只好在容器里运行crond，运行后就跑任务了，觉得还是安装脚本哪里在安装时把crond服务关了或者没启动起来的问题造成的，小白不是太懂，只是猜想

_Originally posted by @wifisky-feilian in https://github.com/TNanko/Scripts/issues/21#issuecomment-753466870_

**Comment by EvineDeng** [comment]
使用2021-01-02 21:07:59这个时间构建的镜像应该好了，暂时未添加日志功能。

之前作者说他来弄定时任务的，所以docker前几天的版本没有弄这个。

另外，作者正在写日志功能，在写好日志功能，镜像还要重新制作。

**Comment by xushen1994** [comment]
群在哪儿求加。。。

**Comment by TNanko** [comment]
> 群在哪儿求加。。。

我是有个 tg 群，里面是我另一个项目，你也可以加进来问我 https://t.me/TuringLabProxyPool

**Comment by EvineDeng** [comment]
因为版本更新，2021-01-02 22:05:35 又一次重新制作了镜像，以这个时间点的镜像为准。

**Comment by TNanko** [comment]
最新版本的源码，我在 centos7 下测试是正常执行定时任务的，正常生成日志（不要使用python虚拟环境）

**Comment by wifisky-feilian** [comment]
> 最新版本的源码，我在 centos7 下测试是正常执行定时任务的，正常生成日志（不要使用python虚拟环境）

这次源码和镜像docker下正常跑任务了 LOGO还专门分类文件夹了带日期，不错不错，感谢两位大佬辛苦付出~
