### ISSUE TITLE
昨天的最新版为什么阅读时长一直为0

### ISSUE THREAD

**Issue by wifisky-feilian** [TNanko/Scripts#28]
昨天的最新版为什么阅读时长一直为0，看了收益明细，只打卡，看视频，宝箱翻倍

☆【企鹅读书】2021-01-03 13:00:03 ☆

【用户昵称】XX
【金币余额】剩余29296金币，可提现2元
【今日收益】4326金币，约0.43元

### _【本周阅读】10小时30分钟（这里还是老版本以前的计数）
【今日阅读】0小时0分钟（今天凌晨12点多安装的，中午看这里一直为0）_

【立即阅读《轮回乐园》】100金币，已完成
【阅读任务】600金币，去阅读
【明日打卡】288金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第1期(1.1-3)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开24个宝箱，下一个宝箱0分钟后领取
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：19.54秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
2021-01-03  13:00:28 Sun TNanko's Scripts INFO

**Comment by TNanko** [comment]
你手动运行一下，看看有没有报错！如果报错，你把报错信息发过来，不然你重新抓下包

**Comment by wifisky-feilian** [comment]
> 你手动运行一下，看看有没有报错！如果报错，你把报错信息发过来，不然你重新抓下包
怎么手动运行呢？

加了个新号新的包，阅读时长也不增加，但有看视频，宝箱等任务

**Comment by TNanko** [comment]
> > 你手动运行一下，看看有没有报错！如果报错，你把报错信息发过来，不然你重新抓下包
> > 怎么手动运行呢？
> 
> 加了个新号新的包，阅读时长也不增加，但有看视频，宝箱等任务

你不按照我上面说的做，我咋找问题

**Comment by wifisky-feilian** [comment]
> > > 你手动运行一下，看看有没有报错！如果报错，你把报错信息发过来，不然你重新抓下包
> > > 怎么手动运行呢？
> > 
> > 
> > 加了个新号新的包，阅读时长也不增加，但有看视频，宝箱等任务
> 
> 你不按照我上面说的做，我咋找问题

手动运行容器，还是手动运行qq_read.py？

**Comment by TNanko** [comment]
手动云翔qq_read.py

**Comment by wifisky-feilian** [comment]
> 手动运行 qq_read.py
> python3 qq_read.py

root@tnanko_scripts:/Scripts/scripts $ python3 qq_read.py
获取最新配置文件版本成功！
当前配置文件为最新版本
当前脚本为最新版本

================【企鹅读书】2021-01-03 06:24:19/2021-01-03 14:24:19 ================

Traceback (most recent call last):
  File "/Scripts/scripts/qq_read.py", line 338, in read_books
    book_url = re.sub(time_in_chapter_info.findall(book_url)[0], str(upload_time_for_url), str(book_url))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Scripts/scripts/qq_read.py", line 341, in read_books
    book_url = re.sub(time_in_chapter_info.findall(book_url)[0], str(upload_time_for_url), str(book_url))
IndexError: list index out of range

2021-01-03  14:24:22 Sun TNanko's Scripts INFO
☆【企鹅读书】2021-01-03 14:24:19 ☆

【用户昵称】XX
【金币余额】剩余29774金币，可提现2元
【今日收益】4804金币，约0.48元
【本周阅读】10小时30分钟
【今日阅读】0小时0分钟
【立即阅读《轮回乐园》】100金币，已完成
【阅读任务】600金币，去阅读
【明日打卡】288金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第1期(1.1-3)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开27个宝箱，下一个宝箱5分钟后领取
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：3.27秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
未进行消息推送，原因：没到对应的推送时间点


================【企鹅读书】2021-01-03 06:24:22/2021-01-03 14:24:22 ================

Traceback (most recent call last):
  File "/Scripts/scripts/qq_read.py", line 338, in read_books
    book_url = re.sub(time_in_chapter_info.findall(book_url)[0], str(upload_time_for_url), str(book_url))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Scripts/scripts/qq_read.py", line 341, in read_books
    book_url = re.sub(time_in_chapter_info.findall(book_url)[0], str(upload_time_for_url), str(book_url))
IndexError: list index out of range

2021-01-03  14:24:26 Sun TNanko's Scripts INFO
☆【企鹅读书】2021-01-03 14:24:22 ☆

【用户昵称】XX1
【金币余额】剩余20324金币，可提现2元
【今日收益】4658金币，约0.47元
【本周阅读】10小时30分钟
【今日阅读】0小时0分钟
【立即阅读《轮回乐园》】100金币，已完成
【阅读任务】600金币，去阅读
【明日打卡】288金币，去查看
【看视频领金币】500金币，已完成(5/5)
【邀请任务】1月第1期(1.1-3)，已邀0人，再邀请1人可获2000金币
【粉丝分成】已有0个粉丝，今日获得分成0金币
【宝箱任务】已开27个宝箱，下一个宝箱6分钟后领取
【数据跟踪】跟踪成功！
【自动提现】未启用该功能
🕛耗时：3.56秒
如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
未进行消息推送，原因：没到对应的推送时间点

**Comment by TNanko** [comment]
晚点修复

**Comment by wifisky-feilian** [comment]
> 晚点修复

好的

**Comment by TNanko** [comment]
> > 晚点修复
> 
> 好的

把你的书籍 url 发过来

**Comment by wifisky-feilian** [comment]
> > > 晚点修复
> > 
> > 
> > 好的
> 
> 把你的书籍 url 发过来，目测是那你的书籍 url 抓错了

书籍 url用的你的模板里的，之前版本阅读时长运行正常的

**Comment by TNanko** [comment]
应该是书籍 url 的问题，你自己抓换本书或者用这个
`https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1132&refer=-1&bid=34207118&readTime=7373&read_type=0&conttype=1&read_status=0&chapter_info=[{"1":{"readTime":7373,"pay_status":0}}]&sp=-1`

**Comment by wifisky-feilian** [comment]
> 应该是书籍 url 的问题，你自己抓换本书或者用这个
> `https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1132&refer=-1&bid=34207118&readTime=7373&read_type=0&conttype=1&read_status=0&chapter_info=[{"1":{"readTime":7373,"pay_status":0}}]&sp=-1`

我重抓的书籍URL和你刚发给我的chapter_info后面为什么不一样？多了一半的代码，但确实可以增加今日阅读时长了
https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=20909208&readTime=25830&read_type=0&conttype=1&read_status=0&chapter_info=[{"1":{"readTime":20670,"pay_status":0,"is_tail":1}},{"2":{"readTime":5160,"pay_status":0,"is_tail":1}}]&sp=-1

**Comment by TNanko** [comment]
> > 应该是书籍 url 的问题，你自己抓换本书或者用这个
> 
> > `https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1132&refer=-1&bid=34207118&readTime=7373&read_type=0&conttype=1&read_status=0&chapter_info=[{"1":{"readTime":7373,"pay_status":0}}]&sp=-1`
> 
> 
> 
> 我重抓的书籍URL和你刚发给我的chapter_info后面为什么不一样？多了一半的代码，但确实可以增加今日阅读时长了
> 
> https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=20909208&readTime=25830&read_type=0&conttype=1&read_status=0&chapter_info=[{"1":{"readTime":20670,"pay_status":0,"is_tail":1}},{"2":{"readTime":5160,"pay_status":0,"is_tail":1}}]&sp=-1

不清楚，代码没啥问题，有问题就重新抓 url 我那个只是例子...

**Comment by wifisky-feilian** [comment]
> > > 应该是书籍 url 的问题，你自己抓换本书或者用这个
> > 
> > 
> > > `https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1132&refer=-1&bid=34207118&readTime=7373&read_type=0&conttype=1&read_status=0&chapter_info=[{"1":{"readTime":7373,"pay_status":0}}]&sp=-1`
> > 
> > 
> > 我重抓的书籍URL和你刚发给我的chapter_info后面为什么不一样？多了一半的代码，但确实可以增加今日阅读时长了
> > [https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=20909208&readTime=25830&read_type=0&conttype=1&read_status=0&chapter_info=[{"1":{"readTime":20670,"pay_status":0,"is_tail":1}},{"2":{"readTime":5160,"pay_status":0,"is_tail":1}}]&sp=-1](https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=20909208&readTime=25830&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22:%7B%22readTime%22:20670,%22pay_status%22:0,%22is_tail%22:1%7D%7D,%7B%222%22:%7B%22readTime%22:5160,%22pay_status%22:0,%22is_tail%22:1%7D%7D%5D&sp=-1)
> 
> 不清楚，代码没啥问题，有问题就重新抓 url 我那个只是例子...

好的，谢谢~
