### ISSUE TITLE
更新后Docker版不会定时运行，手动运行后也没有生成对应的log文件

### ISSUE THREAD

**Issue by zyt821** [TNanko/Scripts#29]

**Comment by zyt821** [comment]
新版查看crontab -l后只有如下2条任务：
root@tnanko_scripts:/Scripts $ crontab -l
55 * * * * git -C /Scripts pull | ts "%Y-%m-%d %H:%M:%S" >> /Scripts/log/git_pull.log 2>&1
25 4 * * 6 chmod +x /Scripts/docker/rm_log.sh && bash /Scripts/docker/rm_log.sh >/dev/null 2>&1
尝试 crontab -e 后添加重启：
*/10 * * * * python3 /Scripts/scripts/qq_read.py # TNanko Scripts

**Comment by zyt821** [comment]
已解决

**Comment by landcruser** [comment]
> 已解决

怎么解决的大佬，我也遇到了
