### ISSUE TITLE
每日打卡不自动打，是我的body有问题吗？

### ISSUE THREAD

**Issue by hengwuming** [TNanko/Scripts#30]

**Comment by hengwuming** [comment]
应该是body的问题，我照着我最开始也可以的自动打卡的配置修改了下body和head就可以自动打卡了

**Comment by hengwuming** [comment]
是cookie里的mpVersion=0.41.0这个问题我改成0.38.2就可以自动打卡了，希望大佬可以看看为什么

**Comment by TNanko** [comment]
> 是cookie里的mpVersion=0.41.0这个问题我改成0.38.2就可以自动打卡了，希望大佬可以看看为什么

强制降低版本，代码已经写好了，我在测试开宝箱的问题，等解决了一起更新脚本

**Comment by hengwuming** [comment]
> > 是cookie里的mpVersion=0.41.0这个问题我改成0.38.2就可以自动打卡了，希望大佬可以看看为什么
> 
> 强制降低版本，代码已经写好了，我在测试开宝箱的问题，等解决了一起更新脚本

好的
