### ISSUE TITLE
docker版手动运行后一堆track back报错，末尾提示header 过期，已检测过不是语法问题

### ISSUE THREAD

**Issue by zyt821** [TNanko/Scripts#31]
一台docker里的容器始终无法更新到最新的版本（remove 容器后重新添加的）容器中的脚本还是旧的，cronb只有git_pull和rm log没有定时qqread.py的任务（手动添加后可以自动运行）。感觉运行起来的是之前不会打印log的版本，其他没啥问题。

因为不敢乱动怕把这台也搞坏了，换了一台机子的docker做测试。容器应该是最新，但是按教程的安装运行后报错，一堆track back的错误（有点多不知道应该截哪一段，就放了个头尾）：
![image](https://user-images.githubusercontent.com/33255990/103509224-974a6800-4e9d-11eb-98fc-593ae0ecafac.png)
![image](https://user-images.githubusercontent.com/33255990/103509254-a7fade00-4e9d-11eb-88dd-9002eb8fb9b0.png)
最后提示 XXX header过期。这个测试的cookie我试过40和41的，都是这个错误。

**Comment by zyt821** [comment]
看了一下说的是连接问题，具体是什么问题不是很懂

**Comment by TNanko** [comment]
> 看了一下说的是连接问题，具体是什么问题不是很懂

这边是有点问题，当时我是笼统的判断下，下一个版本修复这个问题

**Comment by zyt821** [comment]
好的，我再研究一下

**Comment by landcruser** [comment]
我是用教程语句部署docker，脚本是1.4.2，配置是1.5.0，docker启动后没有反应，log文件夹是空的，容器日志直到欢迎的界面，crond[9]: crond (busybox 1.31.1) started, log level 8
开始添加定时任务...
【开始安装 TNanko Scripts ...】
【删除项目旧定时任务...】
【创建项目定时任务...】
【安装成功！】
添加定时任务完成...
Python 3.9.1 (default, Dec 17 2020, 01:59:58) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
开始添加定时任务...
crond[10]: crond (busybox 1.31.1) started, log level 8
【开始安装 TNanko Scripts ...】
【删除项目旧定时任务...】
【创建项目定时任务...】
【安装成功！】
添加定时任务完成...
Python 3.9.1 (default, Dec 17 2020, 01:59:58) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
然后就不动了，请教大佬是脚本太老？还是？重新部署docker也不行，docker的python 3.8  3.9都有
