### ISSUE TITLE
安卓无法运行python多线程

### ISSUE THREAD

**Issue by kingsleyzhnlanf** [TNanko/Scripts#32]
大佬，termux无法运行多线程
显示 ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)

**Comment by TNanko** [comment]
> 大佬，termux无法运行多线程
> 
> 显示 ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.9/lib-dynload/_multiprocessing.cpython-39.so)

emm，账号多的话用 vps 吧，少的话你找下老版本跑跑。

**Comment by kingsleyzhnlanf** [comment]
![image](https://user-images.githubusercontent.com/76804516/103600836-586eed80-4f43-11eb-9901-36c8f4f836ef.png)
![image](https://user-images.githubusercontent.com/76804516/103600856-63298280-4f43-11eb-9fc9-829b2403e870.png)

**Comment by TNanko** [comment]
权限不够的原因，具体[解决方法](https://blog.csdn.net/cn_wk/article/details/80151096)

**Comment by kingsleyzhnlanf** [comment]
我昨天试了，不行，查了一圈是termux没有添加sem_open，因此不管怎么折腾都不能执行python的多线程功能

**Comment by TNanko** [comment]
> 我昨天试了，不行，查了一圈是termux没有添加sem_open，因此不管怎么折腾都不能执行python的多线程功能

不是你是用什么设备跑的？我有点懵，你不是 vps 吗？ termux 只是个终端工具，主要还得你在 vps 提权或者重装 python3.6，你的原因已经告诉你了，实在不行就重装 python3 吧

原因：没有挂载/dev/shm;python安装时需要写入东西，才能开启sem_open

解决办法：（需要root权限；以下命令root账号执行）

1. 修改/etc/fstab 增加：tmpfs /dev/shm tmpfs defaults 0 0

2. mount /dev/shm

3. chmod 777 /dev/shm

4. 重装 python3 （必须重装，没办法，安装时检查该设备是否存在，存在则可以使用sem_open）

**Comment by kingsleyzhnlanf** [comment]
> > 我昨天试了，不行，查了一圈是termux没有添加sem_open，因此不管怎么折腾都不能执行python的多线程功能
> 
> 不是你是用什么设备跑的？我有点懵，你不是 vps 吗？ termux 只是个终端工具，主要还得你在 vps 提权或者重装 python3.6，你的原因已经告诉你了，实在不行就重装 python3 吧
> 
> 原因：没有挂载/dev/shm;python安装时需要写入东西，才能开启sem_open
> 
> 解决办法：（需要root权限；以下命令root账号执行）
> 
> 1. 修改/etc/fstab 增加：tmpfs /dev/shm tmpfs defaults 0 0
> 2. mount /dev/shm
> 3. chmod 777 /dev/shm
> 4. 重装 python3 （必须重装，没办法，安装时检查该设备是否存在，存在则可以使用sem_open）

大佬，我是安卓，不是vps，在termux装了ssh，然后用winscp连接的，这个问题重装也没法解决

**Comment by kingsleyzhnlanf** [comment]
上面的解决方案是针对部分ubuntu系统

**Comment by TNanko** [comment]
> > > 我昨天试了，不行，查了一圈是termux没有添加sem_open，因此不管怎么折腾都不能执行python的多线程功能
> > 
> > 
> > 不是你是用什么设备跑的？我有点懵，你不是 vps 吗？ termux 只是个终端工具，主要还得你在 vps 提权或者重装 python3.6，你的原因已经告诉你了，实在不行就重装 python3 吧
> > 原因：没有挂载/dev/shm;python安装时需要写入东西，才能开启sem_open
> > 解决办法：（需要root权限；以下命令root账号执行）
> > 
> > 1. 修改/etc/fstab 增加：tmpfs /dev/shm tmpfs defaults 0 0
> > 2. mount /dev/shm
> > 3. chmod 777 /dev/shm
> > 4. 重装 python3 （必须重装，没办法，安装时检查该设备是否存在，存在则可以使用sem_open）
> 
> 大佬，我是安卓，不是vps，在termux装了ssh，然后用winscp连接的，这个问题重装也没法解决

好吧，那我也没办法了（ `Android` 还能这样玩？）你尝试找一下老版本的脚本吧（克隆的时候指定 `commit` ，教程百度），不过建议还是上 `vps` 或者本地跑

**Comment by kingsleyzhnlanf** [comment]
好的，我现在是老版本，我试试云函数
