### ISSUE TITLE
我想修改通知时间

### ISSUE THREAD

**Issue by hengwuming** [TNanko/Scripts#35]
我想每开15个宝箱就通知一次，可是 treasure_box_reward['count'] 这个参数是局部变量，一加入最后通知判断就报错，我该怎么弄呢？
顺便问问大佬对修改这个脚本有兴趣吗？
https://raw.githubusercontent.com/Sunert/Scripts/master/Task/dianshijia.js

**Comment by TNanko** [comment]
> 我想每开15个宝箱就通知一次，可是 treasure_box_reward['count'] 这个参数是局部变量，一加入最后通知判断就报错，我该怎么弄呢？
> 顺便问问大佬对修改这个脚本有兴趣吗？
> https://raw.githubusercontent.com/Sunert/Scripts/master/Task/dianshijia.js

我个人觉得没啥必要  treasure_box_reward['count'] / 15 == 0 然后调用下面的推送代码
电视家不是凉了吗

**Comment by hengwuming** [comment]
> > 我想每开15个宝箱就通知一次，可是 treasure_box_reward['count'] 这个参数是局部变量，一加入最后通知判断就报错，我该怎么弄呢？
> > 顺便问问大佬对修改这个脚本有兴趣吗？
> > https://raw.githubusercontent.com/Sunert/Scripts/master/Task/dianshijia.js
> 
> 我个人觉得没啥必要 treasure_box_reward['count'] / 15 == 0 然后调用下面的推送代码
> 电视家不是凉了吗

应该没有把，我看到有人在跑。

**Comment by TNanko** [comment]
好吧，我个人兴趣不大

**Comment by hengwuming** [comment]
> 好吧，我个人兴趣不大

好的
