### ISSUE TITLE
企鹅微信推送问题

### ISSUE THREAD

**Issue by hongyunfei** [TNanko/Scripts#4]
b站微信推送每天都正常收到，企鹅的就是收不到，不知哪里出了问题，请大神指导下

**Comment by TNanko** [comment]
因为企鹅读书每天需要运行多次，所以我设定每天晚上10-10:10之间，如果程序运行，则会发送相应的推送。所以，如果你是使用的 github action ，你可以看下昨晚这个时间段是否运行，如果你是 vps 或者 pc 等，将 cron 设置为 10 分钟运行一次最佳。当然后期我也会改进通知这一块！
