### ISSUE TITLE
配置完成后可以正常启动，但无金币增加。

### ISSUE THREAD

**Issue by zhou2016** [TNanko/Scripts#6]
qq_read.log日志显示如下：
![image](https://user-images.githubusercontent.com/12530673/102762733-a5838900-43b3-11eb-8207-68f8bf4455a4.png)

**Comment by TNanko** [comment]
你是否在 config.yml 文件里的使用任务把参数 enable 设置为 true

**Comment by zhou2016** [comment]
刚刚检查了下，是 config.yml 文件里复制粘贴的时候误删了 WITHDRAW: false  这一行代码。
补全以后，日志显示拒绝连接的错误如下，麻烦大佬帮忙看看，啥原因。
![image](https://user-images.githubusercontent.com/12530673/102764558-483d0700-43b6-11eb-9618-f570606b174c.png)

**Comment by TNanko** [comment]
> 刚刚检查了下，是 config.yml 文件里复制粘贴的时候误删了 WITHDRAW: false  这一行代码。
> 
> 补全以后，日志显示拒绝连接的错误如下，麻烦大佬帮忙看看，啥原因。
> 
> ![image](https://user-images.githubusercontent.com/12530673/102764558-483d0700-43b6-11eb-9618-f570606b174c.png)
> 

你这个咋感觉是包的问题或者是你本地网络的问题

**Comment by zhou2016** [comment]
好的，谢谢大佬。我好好检查一下。
