### ISSUE TITLE
Server酱的通知没有换行呢，大佬看一下

### ISSUE THREAD

**Issue by mengdie101** [TNanko/Scripts#7]
收到就是这样的
☆【企鹅读书】2020-12-22 22:10:26 ☆
【用户昵称】*** 【金币余额】剩余24075金币，可提现2元 【今日收益】8752金币，约0.88元 【本周阅读】20小时0分钟 【今日阅读】10小时0分钟 【立即阅读《穿越六十年代农家女》】100金币，已完成 【阅读任务】600金币，已完成 【明日打卡】500金币，去查看 【看视频领金币】500金币，已完成(5/5) 【邀请任务】12月第8期(12.22-24)，已邀0人，再邀请1人可获2000金币 【粉丝分成】已有0个粉丝，今日获得分成0金币 【宝箱任务】已开47个宝箱，下一个宝箱0分钟后领取 【阅读时长】已达到设置的对大阅读时长，故不增加阅读时长 【数据跟踪】跟踪成功！ 【自动提现】未启用该功能 🕛耗时：2.73秒 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~

**Comment by TNanko** [comment]
> 收到就是这样的
> 
> ☆【企鹅读书】2020-12-22 22:10:26 ☆
> 
> 【用户昵称】*** 【金币余额】剩余24075金币，可提现2元 【今日收益】8752金币，约0.88元 【本周阅读】20小时0分钟 【今日阅读】10小时0分钟 【立即阅读《穿越六十年代农家女》】100金币，已完成 【阅读任务】600金币，已完成 【明日打卡】500金币，去查看 【看视频领金币】500金币，已完成(5/5) 【邀请任务】12月第8期(12.22-24)，已邀0人，再邀请1人可获2000金币 【粉丝分成】已有0个粉丝，今日获得分成0金币 【宝箱任务】已开47个宝箱，下一个宝箱0分钟后领取 【阅读时长】已达到设置的对大阅读时长，故不增加阅读时长 【数据跟踪】跟踪成功！ 【自动提现】未启用该功能 🕛耗时：2.73秒 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
> 
> 

抱歉，这个我没测试，我月底修复一下这个bug，你可以先选择其他推送方式

**Comment by EvineDeng** [comment]
> > 收到就是这样的
> > 
> > ☆【企鹅读书】2020-12-22 22:10:26 ☆
> > 
> > 【用户昵称】*** 【金币余额】剩余24075金币，可提现2元 【今日收益】8752金币，约0.88元 【本周阅读】20小时0分钟 【今日阅读】10小时0分钟 【立即阅读《穿越六十年代农家女》】100金币，已完成 【阅读任务】600金币，已完成 【明日打卡】500金币，去查看 【看视频领金币】500金币，已完成(5/5) 【邀请任务】12月第8期(12.22-24)，已邀0人，再邀请1人可获2000金币 【粉丝分成】已有0个粉丝，今日获得分成0金币 【宝箱任务】已开47个宝箱，下一个宝箱0分钟后领取 【阅读时长】已达到设置的对大阅读时长，故不增加阅读时长 【数据跟踪】跟踪成功！ 【自动提现】未启用该功能 🕛耗时：2.73秒 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
> > 
> > 
> 
> 抱歉，这个我没测试，我月底修复一下这个bug，你可以先选择其他推送方式

serverChan俩换行才是换行....

**Comment by TNanko** [comment]
> > > 收到就是这样的
> > > 
> > > ☆【企鹅读书】2020-12-22 22:10:26 ☆
> > > 
> > > 【用户昵称】*** 【金币余额】剩余24075金币，可提现2元 【今日收益】8752金币，约0.88元 【本周阅读】20小时0分钟 【今日阅读】10小时0分钟 【立即阅读《穿越六十年代农家女》】100金币，已完成 【阅读任务】600金币，已完成 【明日打卡】500金币，去查看 【看视频领金币】500金币，已完成(5/5) 【邀请任务】12月第8期(12.22-24)，已邀0人，再邀请1人可获2000金币 【粉丝分成】已有0个粉丝，今日获得分成0金币 【宝箱任务】已开47个宝箱，下一个宝箱0分钟后领取 【阅读时长】已达到设置的对大阅读时长，故不增加阅读时长 【数据跟踪】跟踪成功！ 【自动提现】未启用该功能 🕛耗时：2.73秒 如果帮助到您可以点下🌟STAR鼓励我一下，谢谢~
> > > 
> > > 
> > 
> > 抱歉，这个我没测试，我月底修复一下这个bug，你可以先选择其他推送方式
> 
> serverChan俩换行才是换行....

好的，我明天晚上更新一下代码。

**Comment by TNanko** [comment]
已修复
